Tracker:AddMaps("maps/maps.json")

Tracker:AddItems("items/equipment.json")
Tracker:AddItems("items/hud.json")
Tracker:AddItems("items/roms.json")
Tracker:AddItems("items/subweapons.json")
Tracker:AddItems("items/weapons.json")

ScriptHost:LoadScript("scripts/logic/logic.lua")

Tracker:AddLocations("locations/00_Surface.json")
Tracker:AddLocations("locations/01_Guidance.json")
Tracker:AddLocations("locations/02_Mausoleum.json")
Tracker:AddLocations("locations/03.json")
Tracker:AddLocations("locations/04.json")
Tracker:AddLocations("locations/05.json")
Tracker:AddLocations("locations/06.json")
Tracker:AddLocations("locations/07.json")
Tracker:AddLocations("locations/08.json")
Tracker:AddLocations("locations/09.json")
Tracker:AddLocations("locations/11.json")
Tracker:AddLocations("locations/12.json")
Tracker:AddLocations("locations/13.json")
Tracker:AddLocations("locations/14.json")
Tracker:AddLocations("locations/15.json")
Tracker:AddLocations("locations/16.json")
Tracker:AddLocations("locations/18.json")

Tracker:AddLayouts("layouts/tracker.json")
Tracker:FindObjectForCode("fake_scanner"):SetOverlay("fake")
Tracker:FindObjectForCode("antarctic_adventure"):SetOverlay("AA")
Tracker:FindObjectForCode("comic_bakery"):SetOverlay("CB")
Tracker:FindObjectForCode("mahjong_wizard"):SetOverlay("MW")
Tracker:FindObjectForCode("castlevania"):SetOverlay("CV")
Tracker:FindObjectForCode("qbert"):SetOverlay("Q*")

-- Tracker.AllowDeferredLogicUpdate = true